### ISSUE TITLE
Lido Subgraph Migration

### ISSUE THREAD

**Issue by hnurzipta** [subsquid-quests/lido-subgraph-migration#4]
Hello,

Could you please check?

Here is the link to the repository.
https://github.com/hnurzipta/lido-subgraph-migration

Thank you.

**Comment by 2ndshadow** [comment]
Hey, @hnurzipta, 
Could you please check your github account is linked to your testnet account here https://app.subsquid.io/profile/settings, so that we can reward you. 
Thanks.

**Comment by hnurzipta** [comment]
Hello @2ndshadow,
Done sir, I have updated to show email in my github profile.

**Comment by 2ndshadow** [comment]
Sorry I don't see any users in the DB with 'hnurzipta' github linked. What's email is used to login to https://app.subsquid.io/?

**Comment by hnurzipta** [comment]
I use `just4u.d33i@gmail.com` to login https://app.subsquid.io @2ndshadow, I just reconnnect github account

<img width="861" alt="Screenshot 2024-01-16 at 19 07 19" src="https://github.com/subsquid-quests/lido-subgraph-migration/assets/24311978/fcddd435-d388-4efd-adf7-589e3dc898e8">
